version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: derdek/cropec-php
        env_file:
            - .env
        volumes:
            - ./:/var/www
        networks:
            - cropec-network

    nginx:
        image: nginx:alpine
        ports:
            - "8002:80"
        volumes:
            - ./:/var/www
            - ./docker-config/nginx/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - cropec-network
networks:
    cropec-network:
        driver: bridge
